# İlk önce bir temel görüntü seçin, genellikle Python için resmi görüntüyü kullanabilirsiniz.
FROM python:3.8

# Çalışma dizinini ayarlayın
WORKDIR /app

# Projenizin gereksinimlerini kopyalayın ve kurun
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Projenizi Docker içine kopyalayın
COPY . /app/

# Gerekli komutları çalıştırın (ödocker build -t 
RUN python manage.py migrate

# Uygulamayı başlatın
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
